function vec = azal2vec(azimuth, altitude)
    vec = ...
        [sin(azimuth) * cos(altitude), ...
         cos(azimuth) * cos(altitude), ...
         sin(altitude)];
    vec = vec / norm(vec(:));
end
